### ISSUE TITLE
Error 2: Appid missing

### ISSUE THREAD

**Issue by unoo** [ironman5366/W.I.L.L#10]
`[20:18:34]: 

\        /   |    |          |
 \          /    |    |          |
  \        /     |    |          |
   \    /\    /      |    |          |
    \  /  \  /       |    |          |
     \/    \/    |    ------------   ------------

[20:18:34]: Debug value is True
[20:18:34]: Connecting to rtm socket
[20:18:34]: Starting flask server on localhost
[20:18:34]: In slack function in new thread
- Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
  Exception in thread Thread-1:
  Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "main.py", line 35, in slack
    message = sc.rtm_read()
  File "/home/ryan/.local/lib/python2.7/site-packages/slackclient/_client.py", line 28, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/ryan/.local/lib/python2.7/site-packages/slackclient/_server.py", line 110, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  AttributeError: 'NoneType' object has no attribute 'recv'

[20:18:40]: Command is 
[20:18:40]: Analyzing content in command
[20:18:40]: Analyzed command content
[20:18:40]: Trying to load plugin modules
[20:18:40]: In plugin loader
[20:18:40]: plugindir is ['plugins', ['open', 'execute', 'autoremote', 'search', 'youtube'], []]
[20:18:40]: Plugin is open
[20:18:40]: Loading plugin open
[20:18:40]: plugin.json file path should be plugins/open/plugin.json
[20:18:40]: Loaded plugin open
[20:18:40]: Plugin is execute
[20:18:40]: Loading plugin execute
[20:18:40]: plugin.json file path should be plugins/execute/plugin.json
[20:18:40]: Loaded plugin execute
[20:18:40]: Plugin is autoremote
[20:18:40]: Loading plugin autoremote
[20:18:40]: plugin.json file path should be plugins/autoremote/plugin.json
[20:18:40]: Loaded plugin autoremote
[20:18:40]: Plugin is search
[20:18:40]: Loading plugin search
[20:18:40]: plugin.json file path should be plugins/search/plugin.json
[20:18:40]: Loaded plugin search
[20:18:40]: Plugin is youtube
[20:18:40]: Loading plugin youtube
[20:18:40]: plugin.json file path should be plugins/youtube/plugin.json
[20:18:40]: Loaded plugin youtube
[20:18:40]: Successfully loaded plugin modules
[20:18:40]: Using the intent module to parse the command
[20:18:40]: Analyzing word 
[20:18:40]: Checking to see if the word is a plugin
[20:18:40]: Full plugin is {'open': [{u'name': u'open'}, {u'type': u'exec'}, {u'require': [u'command']}, {u'pos': u'verb'}, {u'returns': u'completion'}, {u'synonyms': []}, {u'questiontriggers': u'none'}, {u'firstword': u'no'}, {u'structure': u'xdg-open command'}]}
[20:18:40]: Plugin name is open
[20:18:40]: Plugin values are [{u'name': u'open'}, {u'type': u'exec'}, {u'require': [u'command']}, {u'pos': u'verb'}, {u'returns': u'completion'}, {u'synonyms': []}, {u'questiontriggers': u'none'}, {u'firstword': u'no'}, {u'structure': u'xdg-open command'}]
[20:18:40]: Checking dictionary {u'name': u'open'}
[20:18:40]: Checking dictionary {u'type': u'exec'}
[20:18:40]: Checking dictionary {u'require': [u'command']}
[20:18:40]: Checking dictionary {u'pos': u'verb'}
[20:18:40]: Checking dictionary {u'returns': u'completion'}
[20:18:40]: Checking dictionary {u'synonyms': []}
[20:18:40]: Found synonyms dictionary
[20:18:40]: The command does not match the plugin name
[20:18:40]: Full plugin is {'execute': [{u'name': u'execute'}, {u'type': u'exec'}, {u'require': [u'command']}, {u'pos': u'verb'}, {u'returns': u'completion'}, {u'synonyms': []}, {u'questiontriggers': u'none'}, {u'firstword': u'no'}, {u'structure': u'command'}]}
[20:18:40]: Plugin name is execute
[20:18:40]: Plugin values are [{u'name': u'execute'}, {u'type': u'exec'}, {u'require': [u'command']}, {u'pos': u'verb'}, {u'returns': u'completion'}, {u'synonyms': []}, {u'questiontriggers': u'none'}, {u'firstword': u'no'}, {u'structure': u'command'}]
[20:18:40]: Checking dictionary {u'name': u'execute'}
[20:18:40]: Checking dictionary {u'type': u'exec'}
[20:18:40]: Checking dictionary {u'require': [u'command']}
[20:18:40]: Checking dictionary {u'pos': u'verb'}
[20:18:40]: Checking dictionary {u'returns': u'completion'}
[20:18:40]: Checking dictionary {u'synonyms': []}
[20:18:40]: Found synonyms dictionary
[20:18:40]: The command does not match the plugin name
[20:18:40]: Full plugin is {'autoremote': [{u'name': u'autoremote'}, {u'type': u'python'}, {u'file': u'autoremote.py'}, {u'function': u'main'}, {u'require': [u'command']}, {u'pos': u'verb'}, {u'returns': u'completion'}, {u'synonyms': []}, {u'questiontriggers': u'none'}, {u'firstword': u'no'}]}
[20:18:40]: Plugin name is autoremote
[20:18:40]: Plugin values are [{u'name': u'autoremote'}, {u'type': u'python'}, {u'file': u'autoremote.py'}, {u'function': u'main'}, {u'require': [u'command']}, {u'pos': u'verb'}, {u'returns': u'completion'}, {u'synonyms': []}, {u'questiontriggers': u'none'}, {u'firstword': u'no'}]
[20:18:40]: Checking dictionary {u'name': u'autoremote'}
[20:18:40]: Checking dictionary {u'type': u'python'}
[20:18:40]: Checking dictionary {u'file': u'autoremote.py'}
[20:18:40]: Checking dictionary {u'function': u'main'}
[20:18:40]: Checking dictionary {u'require': [u'command']}
[20:18:40]: Checking dictionary {u'pos': u'verb'}
[20:18:40]: Checking dictionary {u'returns': u'completion'}
[20:18:40]: Checking dictionary {u'synonyms': []}
[20:18:40]: Found synonyms dictionary
[20:18:40]: The command does not match the plugin name
[20:18:40]: Full plugin is {'search': [{u'name': u'search'}, {u'type': u'python'}, {u'require': [u'command']}, {u'pos': u'verb'}, {u'file': u'search.py'}, {u'function': u'main'}, {u'returns': u'answer'}, {u'synonyms': [u'google']}, {u'questiontriggers': u'any'}, {u'firstword': u'yes'}]}
[20:18:40]: Plugin name is search
[20:18:40]: Plugin values are [{u'name': u'search'}, {u'type': u'python'}, {u'require': [u'command']}, {u'pos': u'verb'}, {u'file': u'search.py'}, {u'function': u'main'}, {u'returns': u'answer'}, {u'synonyms': [u'google']}, {u'questiontriggers': u'any'}, {u'firstword': u'yes'}]
[20:18:40]: Checking dictionary {u'name': u'search'}
[20:18:40]: Checking dictionary {u'type': u'python'}
[20:18:40]: Checking dictionary {u'require': [u'command']}
[20:18:40]: Checking dictionary {u'pos': u'verb'}
[20:18:40]: Checking dictionary {u'file': u'search.py'}
[20:18:40]: Checking dictionary {u'function': u'main'}
[20:18:40]: Checking dictionary {u'returns': u'answer'}
[20:18:40]: Checking dictionary {u'synonyms': [u'google']}
[20:18:40]: Found synonyms dictionary
[20:18:40]: Checking synonym google
[20:18:40]: The command does not match the plugin name
[20:18:40]: Full plugin is {'youtube': [{u'name': u'youtube'}, {u'type': u'python'}, {u'require': [u'command']}, {u'firstword': u'yes'}, {u'pos': u'verb'}, {u'file': u'youtube.py'}, {u'function': u'main'}, {u'returns': u'completion'}, {u'synonyms': []}, {u'questiontriggers': u'none'}]}
[20:18:40]: Plugin name is youtube
[20:18:40]: Plugin values are [{u'name': u'youtube'}, {u'type': u'python'}, {u'require': [u'command']}, {u'firstword': u'yes'}, {u'pos': u'verb'}, {u'file': u'youtube.py'}, {u'function': u'main'}, {u'returns': u'completion'}, {u'synonyms': []}, {u'questiontriggers': u'none'}]
[20:18:40]: Checking dictionary {u'name': u'youtube'}
[20:18:40]: Checking dictionary {u'type': u'python'}
[20:18:40]: Checking dictionary {u'require': [u'command']}
[20:18:40]: Checking dictionary {u'firstword': u'yes'}
[20:18:40]: Checking dictionary {u'pos': u'verb'}
[20:18:40]: Checking dictionary {u'file': u'youtube.py'}
[20:18:40]: Checking dictionary {u'function': u'main'}
[20:18:40]: Checking dictionary {u'returns': u'completion'}
[20:18:40]: Checking dictionary {u'synonyms': []}
[20:18:40]: Found synonyms dictionary
[20:18:40]: The command does not match the plugin name
[20:18:40]: Checking to see if word  is a question word
[20:18:40]: Checking against question word Who
[20:18:40]: Checking against possible question word Who
[20:18:40]: Checking against possible question word Where
[20:18:40]: Checking against possible question word When
[20:18:40]: Checking against possible question word Why
[20:18:40]: Checking against possible question word What
[20:18:40]: Checking against possible question word Which
[20:18:40]: Checking against possible question word How
[20:18:40]: Checking against possible question word Who's
[20:18:40]: Checking against possible question word Where's
[20:18:40]: Checking against possible question word When's
[20:18:40]: Checking against possible question word Why's
[20:18:40]: Checking against possible question word What's
[20:18:40]: Checking against possible question word Which's
[20:18:40]: Checking against possible question word How's
[20:18:40]: Checking against possible question word Is
[20:18:40]: Checking against possible question word Are
[20:18:40]: Checking against possible question word Am
[20:18:40]: Checking against possible question word Was
[20:18:40]: Checking against possible question word Were
[20:18:40]: Checking against possible question word Will
[20:18:40]: Checking against possible question word Do
[20:18:40]: Checking against possible question word Does
[20:18:40]: Checking against possible question word Did
[20:18:40]: Checking against possible question word Have
[20:18:40]: Checking against possible question word Had
[20:18:40]: Checking against possible question word Has
[20:18:40]: Checking against possible question word Can
[20:18:40]: Checking against possible question word Could
[20:18:40]: Checking against possible question word Should
[20:18:40]: Checking against possible question word Shall
[20:18:40]: Checking against possible question word May
[20:18:40]: Checking against possible question word Might
[20:18:40]: Checking against possible question word Would
[20:18:40]: Command not found
[20:18:40]: Parsed the command
[20:18:40]: Parse function returned the error notfound
[20:18:40]: The error means that the command was not recognized
[20:18:40]: Using the search plugin on the command phrase
[20:18:40]: Trying to find search plugin
[20:18:40]: Found search plugin
[20:18:40]: Executing plugin {'search': [{u'name': u'search'}, {u'type': u'python'}, {u'require': [u'command']}, {u'pos': u'verb'}, {u'file': u'search.py'}, {u'function': u'main'}, {u'returns': u'answer'}, {u'synonyms': [u'google']}, {u'questiontriggers': u'any'}, {u'firstword': u'yes'}]}
[20:18:40]: Looking for type dictionary
[20:18:40]: Checking dictionary {u'name': u'search'}
[20:18:40]: Checking dictionary {u'type': u'python'}
[20:18:40]: Found dictionary type
[20:18:40]: Plugin type is python
[20:18:40]: Looking for firstword dictionary
[20:18:40]: Checking dictionary {u'name': u'search'}
[20:18:40]: Checking dictionary {u'type': u'python'}
[20:18:40]: Checking dictionary {u'require': [u'command']}
[20:18:40]: Checking dictionary {u'pos': u'verb'}
[20:18:40]: Checking dictionary {u'file': u'search.py'}
[20:18:40]: Checking dictionary {u'function': u'main'}
[20:18:40]: Checking dictionary {u'returns': u'answer'}
[20:18:40]: Checking dictionary {u'synonyms': [u'google']}
[20:18:40]: Checking dictionary {u'questiontriggers': u'any'}
[20:18:40]: Checking dictionary {u'firstword': u'yes'}
[20:18:40]: Found dictionary firstword
[20:18:40]: Checking to get the name of the python file
[20:18:40]: Looking for file dictionary
[20:18:40]: Checking dictionary {u'name': u'search'}
[20:18:40]: Checking dictionary {u'type': u'python'}
[20:18:40]: Checking dictionary {u'require': [u'command']}
[20:18:40]: Checking dictionary {u'pos': u'verb'}
[20:18:40]: Checking dictionary {u'file': u'search.py'}
[20:18:40]: Found dictionary file
[20:18:40]: Trying to import python file search.py
[20:18:40]: Import path is plugins/search/search.py
[20:18:40]: Imported python plugin
[20:18:40]: Looking for function dictionary
[20:18:40]: Checking dictionary {u'name': u'search'}
[20:18:40]: Checking dictionary {u'type': u'python'}
[20:18:40]: Checking dictionary {u'require': [u'command']}
[20:18:40]: Checking dictionary {u'pos': u'verb'}
[20:18:40]: Checking dictionary {u'file': u'search.py'}
[20:18:40]: Checking dictionary {u'function': u'main'}
[20:18:40]: Found dictionary function
[20:18:40]: Looking for require dictionary
[20:18:40]: Checking dictionary {u'name': u'search'}
[20:18:40]: Checking dictionary {u'type': u'python'}
[20:18:40]: Checking dictionary {u'require': [u'command']}
[20:18:40]: Found dictionary require
[20:18:40]: In main, query is:
going into wolfram search
[20:18:40]: in wolfram search
[20:18:40]: 
/usr/local/lib/python2.7/dist-packages/wolframalpha/**init**.py:15: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if not error:
[20:18:40]: Error 2: Appid missing
127.0.0.1 - - [26/Feb/2016 20:18:40] "GET / HTTP/1.1" 200 -
`

I might be missing a module but I don't know which one.

Running on Ubuntu 15.10

**Comment by ironman5366** [comment]
You need to enter your appids for slack and wolframalpha. I don't provide keys from my accounts. Somebody's making a configuration file for all the accounts but until then they all have to be entered manually.

**Comment by unoo** [comment]
Okay I entered my Slack appID but where do I enter the wolframalpha ID?

**Comment by vms20591** [comment]
@unoo You can enter your appid in the following file:
W.I.L.L/builtins/search/appidfinal.txt

**Comment by ironman5366** [comment]
@vms20591 That's not where you're supposed to enter it. You're supposed to enter it in appid.txt and that let's you enter multiple keys and cycle through them when you reach the 2000 monthly limit. This is all done automatically

**Comment by vms20591** [comment]
@ironman5366 aahhh Thanks. Got confused by both file :) :)
